[project]
name = "blitz"
version = "1.3.1"
description = "Bulk Loading and Interactive Time series Zonal analysis"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Richard Krieg", email = "alienkrieg@gmail.com" },
    { name = "Philipp Mattern", email = "philipp.mattern@inp-greifswald.de" }
]
license = { text = "GPL-3.0" }
dependencies = [
    "numpy>=2.0.2",
    "opencv-python>=4.10.0.84",
    "natsort>=8.4.0",
    "requests>=2.32.3",
    "python-socketio>=5.11.4",
    "pydicom>=3.0.1",
    "gdcm>=1.1",
    "pylibjpeg>=2.0.1",
    "pylibjpeg-libjpeg>=2.3.0",
    "psutil>=6.1.0",
    "pyqtgraph>=0.13.7",
    "qdarkstyle>=3.2.3",
    "pyqt5==5.15.11",
]

[project.scripts]
blitz = "blitz_main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pyinstaller>=6.16.0",
    "ruff>=0.4.0",
    "pytest>=8.0.0",
]
